<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-02 at 11:53:16.
 */
class UserErrorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var UserError
     */
    protected $error1;
    protected $error2;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->error1 = new UserError("Testnachricht mit 400");
        $this->error2 = new UserError("Testnachricht mit 301", 301);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers UserError::get_json
     * @todo   Implement testGet_json().
     */
    public function testGet_json() {
        $test_error1 = '{"message": "Testnachricht mit 400", "code": "400"}';
        $test_error2 = '{"message": "Testnachricht mit 301", "code": "301"}';
        
        $this->assertEquals($test_error1, $this->error1->get_json());
        $this->assertEquals($test_error2, $this->error2->get_json());
    }

}
